export const metadata = {
  title: 'crmv1',
  description: 'Generated by AgentForge',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="de">
      <body>{children}</body>
    </html>
  )
}